# -*- coding: utf-8 -*-
"""5_test_fish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kaW_FbkcBYK0aEUucwhhij6hKlT3uyBW
"""

import numpy as np
import pandas as pd

fish = pd.read_csv('https://raw.githubusercontent.com/wizard113/ML-Basic/main/fish_data.csv')

fish.head()

fish.describe()

## Data, Target 분리

np.unique(fish['Species'], return_counts=True)

fish.columns

input= fish[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].to_numpy()
target = fish['Species'].to_numpy()

from sklearn.preprocessing import StandardScaler

# 표준화
ss = StandardScaler()
ss.fit(input)
input_scaled = ss.transform(input)
print(input_scaled[0])

## Train, Test 분리

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

x_train, x_test, y_train, y_test = train_test_split(input_scaled, target, test_size=0.2, random_state=23)

print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

## Model 생성

from tensorflow.keras import models, layers, utils

model = models.Sequential()
model = models.Sequential([
    layers.Dense(16, activation='relu', input_shape=(5,)),
    layers.Dense(8, activation='relu'),
    layers.Dense(7, activation='softmax')  # 물고기 종류 7개
])
model.summary()

print(y_train.shape, y_test.shape)

print(y_train)

# 문자열 → 숫자 : one-hot encoding을 위함(여기서는 사용하지 않아도 됨)
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

# one-hot encoding : 분류이므로 사용하지 않아도 됨
y_train_oh = utils.to_categorical(y_train)
y_test_oh = utils.to_categorical(y_test)
print(y_train_oh.shape, y_test_oh.shape)

print(y_train_oh[:10])

# 분류이므로 sparse_categorical_crossentropy
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=100)

# 모델 평가
model.evaluate(x_test, y_test)

y_test[:10]

# 예측
pred = model.predict(x_test[:10])
print(pred)

pred_index = np.argmax(pred, axis=1)
print(pred_index)

fish_type = ['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish']
for p in pred_index:
  print(fish_type[p])

