# -*- coding: utf-8 -*-
"""matplotlib_blank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IOg8tw4QcP3rjJHl9ySQYNBRz0R7eHt_

![matplotlib logo](http://drive.google.com/uc?export=view&id=1lBiIFTqBQSr3lyOH6ifDi28n-EsVBWvr)
## Matplotlib

###*   파이썬용 시각화 라이브러리 이다.
###*   라인플롯, 바 차트, 파이차트, 히스토그램 등의 차트와 플롯 등 다양한 스타일 지원
###*   머신러닝시 데이터 분석이나 결과 확인을 위한 시각화에 사용
###*   [Matplotlib Gallary](https://matplotlib.org/gallery.html)

### matplotlib를 import 해서 간단한 Line Chart 그리기
"""

import matplotlib

matplotlib.pyplot.plot([1, 2, 3, 4], [4, 6, 7, 9])
matplotlib.pyplot.show()
# [1,2,3,4] -> x축, [4,6,7,9] -> y축

"""* 코드를 간결하게 사용하기 위해서 matplotlib의 pyplot을 import하고 plt라고 alias를 설정

* plt.plot([x데이터], y데이터)

* '[ ]'(대괄호)안에 있는 내용은 생략가능, x데이터가 생략될 경우에 x데이터는 0부터 y데이터의 갯수만큼 1씩증가



"""

from matplotlib import pyplot as plt
import numpy as np

plt.plot([1, 2, 3, 4], [4, 6, 7, 9])
plt.show()

plt.plot([4, 6, 7, 9])
plt.show()
# x축이 없음, 기본으로 0부터 시작함

"""### 차트 제목, 축 이름 설정"""

plt.plot(["Seoul","Paris","Seattle"], [30,25,55])
plt.xlabel('City')
plt.ylabel('Response')
plt.title('Experiment Result')
plt.show()

"""### 복수의 데이터사용"""

plt.plot([1,2,3],[1,4,9])
plt.plot([2,3,4],[5,6,7])
plt.xlabel('Sequence')
plt.ylabel('Time(secs)')
plt.title('Experiment Result')
plt.show()

"""### 범례(legend) 설정"""

plt.plot([1,2,3],[1,4,9])
plt.plot([2,3,4],[5,6,7])
plt.xlabel('Sequence')
plt.ylabel('Time(secs)')
plt.legend(['CAT', 'DOG'])
plt.show()

"""### plot함수의 매개변수들

* plot(\*args, scalex=True, scaley=True, data=None, \**kwargs)
* 매개변수에 \* 하나인것은 tuple
* 매개변수에 \** 두개인것은 dictionary

#### args

plot([x데이터1], y데이터1, [fmt], [x데이터2], y데이터2, [fmt], [x데이터3], y데이터3, [fmt],.....)
"""

plt.plot([1,2,3,4],[3,4,5,6],[2,3,4,5],[6,7,8,9])
plt.show()

"""fmt = '[color][maker][line]'


* color-라인의 색깔을 설정
* marker - 마커모양 설정
* line - 라인의 모양을 결정
<p><strong>Markers</strong></p>
<table border="1" class="docutils">
<colgroup>
<col width="30%" />
<col width="70%" />
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">character</th>
<th class="head">description</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'.'</span></code></td>
<td>point marker</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">','</span></code></td>
<td>pixel marker</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'o'</span></code></td>
<td>circle marker</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'v'</span></code></td>
<td>triangle_down marker</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'^'</span></code></td>
<td>triangle_up marker</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'&lt;'</span></code></td>
<td>triangle_left marker</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'&gt;'</span></code></td>
<td>triangle_right marker</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'1'</span></code></td>
<td>tri_down marker</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'2'</span></code></td>
<td>tri_up marker</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'3'</span></code></td>
<td>tri_left marker</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'4'</span></code></td>
<td>tri_right marker</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'s'</span></code></td>
<td>square marker</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'p'</span></code></td>
<td>pentagon marker</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'*'</span></code></td>
<td>star marker</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'h'</span></code></td>
<td>hexagon1 marker</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'H'</span></code></td>
<td>hexagon2 marker</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'+'</span></code></td>
<td>plus marker</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'x'</span></code></td>
<td>x marker</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'D'</span></code></td>
<td>diamond marker</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'d'</span></code></td>
<td>thin_diamond marker</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'|'</span></code></td>
<td>vline marker</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'_'</span></code></td>
<td>hline marker</td>
</tr>
</tbody>
</table>
<p><strong>Line Styles</strong></p>
<table border="1" class="docutils">
<colgroup>
<col width="30%" />
<col width="70%" />
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">character</th>
<th class="head">description</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'-'</span></code></td>
<td>solid line style</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'--'</span></code></td>
<td>dashed line style</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'-.'</span></code></td>
<td>dash-dot line style</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">':'</span></code></td>
<td>dotted line style</td>
</tr>
</tbody>
</table>
<p><strong>Colors</strong></p>
<p>The supported color abbreviations are the single letter codes</p>
<table border="1" class="docutils">
<colgroup>
<col width="30%" />
<col width="70%" />
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">character</th>
<th class="head">color</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'b'</span></code></td>
<td>blue</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'g'</span></code></td>
<td>green</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'r'</span></code></td>
<td>red</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'c'</span></code></td>
<td>cyan</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'m'</span></code></td>
<td>magenta</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'y'</span></code></td>
<td>yellow</td>
</tr>
<tr class="row-even"><td><code class="docutils literal notranslate"><span class="pre">'k'</span></code></td>
<td>black</td>
</tr>
<tr class="row-odd"><td><code class="docutils literal notranslate"><span class="pre">'w'</span></code></td>
<td>white</td>
</tr>
</tbody>
</table>
"""

plt.plot([1,2,3,4],[3,4,5,6],'g-o',[2,3,4,5],[6,7,8,9], 'dm:')
plt.show()

"""
#### data - 딕셔너리로 구성된 데이터를 입력할때 사용
"""

dataplot = {'x_value':[1,2,3,4], 'y_value':[4,5,6,7]}
plt.plot('x_value', 'y_value', data=dataplot)
plt.show()

"""#### \**kwargs
[참조](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.plot.html#matplotlib.pyplot.plot)

#### Scale 조정

* xlim(left=2, right=2)
* ylim(bottom =1,  top=15)
"""

plt.plot([1,2,3,4,5,6,7,8],[3,4,5,6,8,7,6,5],'g-^',[2,3,4,5,],[6,7,8,9],'dm--')
plt.xlim(left=-1, right=10)
plt.ylim(bottom=1, top=15)
plt.show()

"""### subplot
* 두개이상의 차트가 필요할때 사용
"""

x1 = np.linspace(0.0, 5.0)
x2 = np.linspace(0.0, 2.0)

y1 = np.cos(2 * np.pi * x1) * np.exp(-x1)
y2 = np.cos(2 * np.pi * x2)

plt.subplot(2, 1, 1) # 세로 2줄, 가로 1줄, 첫번째 차트
plt.plot(x1, y1, 'o-c')
plt.title('A tale of 2 subplots')

plt.subplot(2, 1, 2)
plt.plot(x2, y2, 'd--')
plt.title('B tale of 2 subplots')
plt.show()

x = np.arange(1,10)
y1 = x*5
y2 = x*1

plt.subplot(1,2,1)
plt.plot(x,y1,'o-')
plt.subplot(1,2,2)
plt.plot(x, y2,'o-g')
plt.show()

x = np.arange(1,10)
y1 = x*5
y2 = x*1
y3 = x*0.3
y4 = x*0.2

plt.subplot(2,2,1)
plt.plot(x, y1, 'bo-')
plt.subplot(2,2,2)
plt.plot(x, y2, 'go-')
plt.subplot(2,2,3)
plt.plot(x, y3, 'ro-')
plt.subplot(2,2,4)
plt.plot(x, y4, 'co-')
plt.show()

x = np.arange(1,10)
y1 = x*5
y2 = x*1
y3 = x*0.3
y4 = x*0.2

"""### Bar chart"""

y = [5, 3, 7, 10, 9, 5, 3.5, 8]
x = range(len(y))

plt.bar(x, y)
plt.bar(x, y, width=0.7, color='blue')
plt.show()

"""### Pie chart"""

labels = ['Apple', 'Samsumg', 'LG', 'HUAWEI']
sizes = [35, 25, 10, 30]  # 합계 100%
colors = ['yellowgreen', 'gold', 'lightskyblue', 'lightcoral']
explode = (0.2, 0.1, 0, 0)  # 중심에서 떨어진 거리
plt.title('Pie Chart')
plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%.2f%%', shadow=True, startangle=90)
plt.show()

"""### scatter (산포도)"""

np.random.seed(0) # random seed는 하나로 고정해놓고 시작하자(그래야 동일 데이터로 나옴)
X = np.random.normal(0, 1, 100) # random.nomrl : 정규분포로....
Y = np.random.normal(0, 1, 100)
plt.scatter(X,Y)
plt.show()